### ISSUE TITLE
V9 support

### ISSUE THREAD

**Issue by ravingdragoon** [jessev14/off-token-status-effects#1]
Any chance you can update this module for Foundry V9?

**Comment by jessev14** [comment]
Yeah it should be an easy update. Could you let me know how you found this module though? I honestly don't remember making it, and I didn't publish it on the Foundry package manager.

**Comment by ravingdragoon** [comment]
I installed your colors and rarities module and looked to see if you had any other cool modules in your repository, where I found this handy little module.

**Comment by jessev14** [comment]
You can update the module in Foundry and it should give you the v9 compatible version now!

**Comment by ravingdragoon** [comment]
Seems to be working great! Thank you so much! I highly recommend publishing this to Foundry if you haven't already. It is so nice to be able to see my full tokens!

**Comment by jessev14** [comment]
Just a heads up, I'm going to delete this repository after I make a new one to officially publish the module. The new module name will be "Status Icon Tweaks."
